### ISSUE TITLE
Arm detection build issue

### ISSUE THREAD

**Issue by lbudai** [Snaipe/BoxFort#23]
I'm building boxfort with criterion in OBS[1] and OBS reports the architecture as 'armv7l'...
After I modified the CMakeLists.txt (just simply added the 'armv7l') OBS was able to build Criterion.

Testing is in progress.
If possible, could you fix the arm detection?

[1] https://build.opensuse.org/package/show/home:laszlo_budai:syslog-ng/criterion

**Comment by Snaipe** [comment]
I'm in the process of transitioning BoxFort and Criterion to use meson instead of cmake. I'm not too keen on fixing it in cmake as I'm going to remove the CMakeLists.txt eventually (as in, when Criterion is done transitioning), but with a new minor release for Criterion already in the work, it's probably okay to include the fix.

Can you open a PR?
